# Generated by Django 3.2.3 on 2021-05-31 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload')),
                ('organizer', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField(blank=True)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField(blank=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
