# Generated by Django 3.2.3 on 2021-06-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210614_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='images/blank.jpg', null=True, upload_to='upload/'),
        ),
    ]
