# Generated by Django 3.2.3 on 2021-06-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210617_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Kultura', 'Kultura'), ('Muzyka', 'Muzyka'), ('Sport', 'Sport'), ('Inne', 'Inne')], default='Kultura', max_length=50),
            preserve_default=False,
        ),
    ]
